kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8082
        hostPort: 8082
        protocol: TCP
      - containerPort: 8080
        hostPort: 8090
        protocol: TCP
