apiVersion: apps/v1
kind: Deployment
metadata:
  name: redokube
  labels:
    app: redokube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redokube
  template:
    metadata:
      labels:
        app: redokube
    spec:
      serviceAccountName: redokube
      containers:
      - name: redokube
        image: redokube:latest
        imagePullPolicy: Never
        args:
        - "--health-probe-bind-address=:8081"
        - "--port=8082"
        - "--external-url=http://localhost:8082"
        - "--spec-directory=/data/specs"
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        - containerPort: 8082
          name: docs
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: spec-storage
          mountPath: /data/specs
      volumes:
      - name: spec-storage
        emptyDir: {}
