apiVersion: v1
kind: ServiceAccount
metadata:
  name: redokube
  labels:
    app: redokube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redokube-role
rules:
  - apiGroups: ["docs.redokube.io"]
    resources: ["openapispecs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["docs.redokube.io"]
    resources: ["openapispecs/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["docs.redokube.io"]
    resources: ["openapispecs/finalizers"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redokube-rolebinding
subjects:
  - kind: ServiceAccount
    name: redokube
    namespace: default
roleRef:
  kind: ClusterRole
  name: redokube-role
  apiGroup: rbac.authorization.k8s.io
