apiVersion: v1
kind: Service
metadata:
  name: redokube
  labels:
    app: redokube
spec:
  selector:
    app: redokube
  ports:
    - name: docs
      port: 8082
      targetPort: docs
    - name: metrics
      port: 8080
      targetPort: metrics
  type: ClusterIP
