apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openapispecs.docs.redokube.io
spec:
  group: docs.redokube.io
  names:
    kind: OpenAPISpec
    listKind: OpenAPISpecList
    plural: openapispecs
    singular: openapispec
    shortNames:
      - apispec
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              anyOf:
                - required: ["title", "specPath"]
                - required: ["title", "specContent"]
              properties:
                title:
                  type: string
                  description: "Title of the API documentation"
                specPath:
                  type: string
                  description: "Path to the OpenAPI specification file or URL"
                specContent:
                  type: string
                  description: "Direct OpenAPI specification content in JSON or YAML format"
                description:
                  type: string
                  description: "Optional description for the API"
                version:
                  type: string
                  description: "Version of the API documentation"
                mock:
                  type: boolean
                  description: "When enabled, generates fake examples for the OpenAPI specification"
                  default: false
                theme:
                  type: object
                  additionalProperties:
                    type: string
                  description: "Theme customization options for Redoc"
            status:
              type: object
              properties:
                status:
                  type: string
                  description: "Represents the current state of the OpenAPISpec"
                  enum: ["Pending", "Available", "Failed"]
                url:
                  type: string
                  description: "URL where the documentation is available"
                lastUpdated:
                  type: string
                  format: date-time
                  description: "Last time the documentation was updated"
                errorMessage:
                  type: string
                  description: "Error message in case of failure"
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.status
        - name: URL
          type: string
          jsonPath: .status.url
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
